# Generated by Django 5.2.9 on 2026-01-15 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_production_movieinfo_production_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='production_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.production'),
        ),
    ]
